name: Build VSIX

permissions:
  contents: write

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Install VSCE
        run: npm install -g vsce

      - name: Package VSIX
        run: npm run package

      - name: Upload VSIX artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: vsix
          path: '*.vsix'

      - name: Upload VSIX to Release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: '*.vsix'
          asset_name: show-unsaved-changes-${{ github.event.release.tag_name }}.vsix
          asset_content_type: application/octet-stream